glorious-codes/glorious-pitsby

src/webapp/scripts/components/external-component-example/external-component-example.html, src/webapp/scripts/components/external-component-example/external-component-example.js, src/webapp/scripts/components/external-component-example/external-component-example.test.js, src/webapp/scripts/components/external-component-examples-list/external-component-examples-list.html, src/webapp/scripts/components/tabs/tabs.html, src/webapp/scripts/components/tabs/tabs.js, src/webapp/scripts/components/tabs/tabs.test.js, src/webapp/scripts/constants/routes.js, src/webapp/scripts/services/index.js, src/webapp/scripts/services/route.js, src/webapp/scripts/services/route.test.js, src/webapp/scripts/services/tabs-route-params.js, src/webapp/scripts/services/tabs-route-params.test.js, webpack.conf.dev.js
Resolves https://github.com/glorious-codes/pitsby/issues/2
Keeping tabs state on url
=> Improve tabs component

.circleci/config.yml, .circleci/prepare.js, package.json, src/cli/services/webapp-html-index-generator.js, src/cli/services/webapp-html-index-generator.test.js, src/cli/services/webapp-index-generator.js, src/cli/services/webapp-index-generator.test.js, src/webapp/scripts/resources/data.test.js
Created specif build script for CI to handle with `index.html` and `index.js` generation.
=> CI configuration improvements

package-lock.json
`package-lock.json`  was not updated in accordance with `package.json`.
- Regenerated `package-lock.json`
- Updated dependency containing vulnerability
=> Dependencies upgrade

package-lock.json, package.json, src/cli/services/external-components-data-generator.js, src/cli/services/external-components-data-generator.test.js, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/components/external-component-preview/external-component-preview.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/20
=>  Keep with functions present in example data

src/webapp/scripts/components/external-component-example/external-component-example.html, src/webapp/scripts/components/external-component-example/external-component-example.js, src/webapp/scripts/components/external-components-list/external-components-list.js, src/webapp/scripts/components/external-components-list/external-components-list.test.js, src/webapp/scripts/components/tabs/tabs.js, src/webapp/scripts/components/tabs/tabs.test.js, src/webapp/scripts/constants/external-component-query-params.js, src/webapp/scripts/constants/routes.js, src/webapp/scripts/services/route-path.js, src/webapp/scripts/services/route-path.test.js, src/webapp/scripts/services/route.js, src/webapp/scripts/services/route.test.js, src/webapp/scripts/services/tabs-route-params.js, src/webapp/scripts/services/tabs-route-params.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/22
=> Add query param group key to tabs component

package-lock.json, package.json, src/cli/services/external-components-data-generator.js, src/cli/services/external-components-data-generator.test.js, src/cli/services/json.js, src/cli/services/json.test.js, src/webapp/scripts/components/external-component-preview/external-component-preview.js
Stringifying and parsing functions when generating/reading external components JSON.
=> JSON functions

package-lock.json, package.json, src/cli/services/external-components-data-generator.js, src/cli/services/external-components-data-generator.test.js, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/components/external-component-preview/external-component-preview.test.js
Allow to write a controller in component data
=> Components data improvement

package-lock.json, package.json, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, src/cli/services/external-assets-generator.js, src/cli/services/external-assets-generator.test.js, src/cli/services/file.js, src/cli/services/file.test.js
Also:
- Minor refactoring on file serviceto use raw console
- Add fs-extra to file service to easier performe tasks like copy
=> Copy some external resources other than styles or scripts

package-lock.json, package.json, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/components/external-component-preview/external-component-preview.test.js
Example controllers for external components now supporting angular dependencies like `$window`, `$timeout`, etc as well as any other third party dependency.
=> Example controller dependencies

src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/config.js, src/cli/services/config.test.js, src/cli/services/external-components-data-generator.js, src/cli/services/external-components-data-generator.test.js, src/cli/services/external-projects-data-generator.js, src/cli/services/external-projects-data-generator.test.js, src/cli/services/webapp-data.js, src/cli/services/webapp-data.test.js, src/cli/services/webapp-html-index-generator.js, src/cli/services/webapp-html-index-generator.test.js, src/cli/services/webapp-index-generator.js, src/cli/services/webapp-index-generator.test.js, src/webapp/mocks/components.js, src/webapp/scripts/components/external-component/external-component.js, src/webapp/scripts/components/external-component/external-component.test.js, src/webapp/scripts/components/external-components-list/external-components-list.js, src/webapp/scripts/components/external-components-list/external-components-list.test.js, src/webapp/scripts/index-template.js, src/webapp/scripts/resources/components.js, src/webapp/scripts/resources/components.test.js, webpack.conf.base.js
This PR resolves first two items listed on https://github.com/glorious-codes/glorious-pitsby/issues/13
=> Read Vue components

.eslintrc.json, package-lock.json, package.json, src/cli/services/json.js, src/cli/services/json.test.js, src/webapp/mocks/global.js, src/webapp/scripts/components/external-component-example/external-component-example.html, src/webapp/scripts/components/external-component-example/external-component-example.js, src/webapp/scripts/components/external-component-example/external-component-example.test.js, src/webapp/scripts/components/external-component-examples-list/external-component-examples-list.html, src/webapp/scripts/components/external-component-examples-list/external-component-examples-list.js, src/webapp/scripts/components/external-component-examples-list/external-component-examples-list.test.js, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/components/external-component-preview/external-component-preview.test.js, src/webapp/scripts/components/external-component/external-component.html, src/webapp/scripts/components/external-component/external-component.js, src/webapp/scripts/components/external-component/external-component.test.js, src/webapp/scripts/services/angular-component-builder.js, src/webapp/scripts/services/angular-component-builder.test.js, src/webapp/scripts/services/dom.js, src/webapp/scripts/services/dom.test.js, src/webapp/scripts/services/index.js, src/webapp/scripts/services/vue-component-builder.js, src/webapp/scripts/services/vue-component-builder.test.js
Ref.: https://github.com/glorious-codes/glorious-pitsby/issues/13
- Handle shorthanded function in json service
- Create DOM service
- Create Angular component builder
- Add Vue and nanoid to the project
- Create Vue component builder
- Render vue components
=> Render Vue example

.eslintrc.json, src/cli/services/args.js, src/cli/services/args.test.js, src/cli/services/config.js, src/cli/services/config.test.js, src/cli/services/webapp-html-index-generator.js, src/cli/services/webapp-html-index-generator.test.js, src/webapp/scripts/components/external-component-example/external-component-example.html
Resolves: #34 #42 
- Allow config file to be written in javascript.
- Improve args service to get specific argument value.
- Use the angular version declared in package.json on angular script tag to be added to index.html.
- Revise external assets (styles/scripts) with timestamp query param to invalidate browser caching.
- Use angular/vue minified scripts when environment is production.
**Also**
- Do not render example controller tab when the example has no controller.
=> Enhancements for config file and web app html index

package-lock.json, package.json, src/cli/commands/build.js, src/cli/docs/build.txt, src/cli/services/bundler.js, src/cli/services/bundler.test.js, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, webpack.conf.base.js, webpack.conf.builder.js, webpack.config.js
=> Production mode fixes

package-lock.json, package.json, src/webapp/styles/tabs.styl
Minor visual improvement on tabs component.
=> Tabs content overflow

package-lock.json, package.json, webpack.conf.base.js, webpack.conf.dev.js, webpack.config.js
- Moved source map plugin to base config. Prod config was missing this plugins and no files were being outputted.
=> Webpack config fix

jest.config.js, package-lock.json, package.json, project.json, src/cli/commands/build.js, src/cli/commands/build.test.js, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, src/cli/services/external-assets-generator.js, src/cli/services/external-assets-generator.test.js, src/cli/services/file.js, src/cli/services/file.test.js, webpack.conf.base.js, webpack.conf.dev.js, webpack.conf.prod.js, webpack.config.js
**Also:** Removing external directories from webapp on docs generation complete.
=> Fix copy external assets issue.

package-lock.json, package.json, webpack.conf.base.js, webpack.conf.dev.js, webpack.conf.prod.js, webpack.config.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/54
=> Improve configuration for production build

package-lock.json, package.json, src/cli/commands/build.test.js, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, src/cli/services/external-components-data-generator.js, src/cli/services/external-components-data-generator.test.js, src/cli/services/external-projects-data-generator.js, src/cli/services/external-projects-data-generator.test.js, src/cli/services/file.js, src/cli/services/file.test.js, src/cli/services/webapp-data.js, src/cli/services/webapp-data.test.js, src/cli/services/webapp-html-index-generator.js, src/cli/services/webapp-html-index-generator.test.js, src/cli/services/webapp-index-generator.js, src/cli/services/webapp-index-generator.test.js
Also, made all write file processes async now on.
=> Replace writefile dependency for file-system

.circleci/config.yml, README.md, docs/configuration.md, docs/contributing.md, docs/documentation.md, package-lock.json, package.json
=> Project's documentation improvements

package-lock.json, package.json, src/webapp/scripts/components/external-component-code/external-component-code.js, src/webapp/scripts/components/external-component-code/external-component-code.test.js, src/webapp/scripts/components/external-component-example/external-component-example.html, src/webapp/scripts/components/external-component-example/external-component-example.test.js, src/webapp/scripts/components/external-component-examples-list/external-component-examples-list.test.js, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/services/code.js, src/webapp/scripts/services/code.test.js, src/webapp/scripts/services/text.js
=> Fix vue controller code in example controller tab

README.md, docs/configuration.md, docs/contributing.md, package-lock.json, package.json
Fixed typos and several gramar mistakes.
=>  Improve grammar on markdown files

package-lock.json, package.json, src/webapp/scripts/views/external-components.html, src/webapp/styles/_native.styl, src/webapp/styles/container.styl, src/webapp/styles/engine-menu.styl, src/webapp/styles/topbar.styl
- Set Inter font family: https://rsms.me/inter/
- Made application container wider (1440px)
=>  Improve UI

src/cli/services/external-components-data-generator.js, src/cli/services/external-components-data-generator.test.js
=> Fix generation of component ID

.circleci/prepare.js, docs/configuration.md, jest.config.js, package-lock.json, package.json, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/external-components-data-generator.js, src/cli/services/external-components-data-generator.test.js, src/cli/services/external-metrics-ids-module-generator.js, src/cli/services/external-metrics-ids-module-generator.test.js, src/cli/services/external-projects-data-generator.js, src/cli/services/external-projects-data-generator.test.js, src/cli/services/webapp-data.js, src/cli/services/webapp-data.test.js, src/cli/services/webapp-index-generator.test.js, src/webapp/mocks/transitions-provider.js, src/webapp/scripts/index-template.js, src/webapp/scripts/index-template.test.js, src/webapp/scripts/router.js, src/webapp/scripts/router.test.js, src/webapp/scripts/services/analytics.js, src/webapp/scripts/services/analytics.test.js, webpack.conf.base.js
Integrates Pitsby with Google Analytics
=> Create Analytics Service

package-lock.json, package.json, src/webapp/scripts/components/engine-menu/engine-menu.js, src/webapp/scripts/components/main/main.js, src/webapp/scripts/components/main/main.test.js, src/webapp/scripts/resources/projects.js, src/webapp/scripts/resources/projects.test.js
No longer trying to check for number of engines querying elements on document. Using projects resource instead.
=> Refactor main component

package-lock.json, package.json, src/webapp/styles/external-components-list.styl
Added side margins to the alert present in external components list
=> Minor visual improvement

docs/documentation.md, package-lock.json, package.json, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/components/external-component-preview/external-component-preview.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/79
=> Component preview styles

package-lock.json, package.json, src/webapp/scripts/components/external-component-code/external-component-code.js, src/webapp/scripts/components/external-component-code/external-component-code.test.js, src/webapp/scripts/services/code-indentation.js, src/webapp/scripts/services/code-indentation.test.js, src/webapp/scripts/services/engine-redirection.js, src/webapp/scripts/services/engine-redirection.test.js, src/webapp/scripts/services/text.js, src/webapp/scripts/services/text.test.js, src/webapp/scripts/services/vue-controller-indentation.js, src/webapp/scripts/services/vue-controller-indentation.test.js, src/webapp/scripts/services/vue-controller-syntax.js, src/webapp/scripts/services/vue-controller-syntax.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/63
=> Improve code indentation

package-lock.json, package.json, src/webapp/scripts/components/external-component-code/external-component-code.js, src/webapp/styles/_variables.styl, src/webapp/styles/alert.styl, src/webapp/styles/btn.styl, src/webapp/styles/external-component-code.styl
A little customisation for PrismJS:
=> Code syntax visual improvement

package-lock.json, package.json, src/webapp/scripts/services/pubsub.js
Refactored some names and the implementation for publish method
=>  Improve pubsub service

docs/configuration.md, package-lock.json, package.json
=> Config doc improvement

package-lock.json, package.json, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/webapp-index-generator.js, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/components/external-component-preview/external-component-preview.test.js, src/webapp/scripts/services/vanilla-component-builder.js, src/webapp/scripts/services/vanilla-component-builder.test.js
=> Add support to vanilla components

README.md, docs/configuration.md, docs/documentation.md, package-lock.json, package.json
Updated configuration and documentation markdowns with vanilla examples.
=>  Add docs for vanilla components

package-lock.json, package.json, src/webapp/scripts/components/external-component-code/external-component-code.html, src/webapp/scripts/components/external-component/external-component.html, src/webapp/scripts/components/index.js, src/webapp/scripts/components/input/input.html, src/webapp/scripts/components/input/input.js, src/webapp/scripts/components/input/input.test.js, src/webapp/scripts/components/paragraph/paragraph.html, src/webapp/scripts/components/paragraph/paragraph.js, src/webapp/scripts/components/paragraph/paragraph.test.js, src/webapp/scripts/components/pre/pre.html, src/webapp/scripts/components/pre/pre.js, src/webapp/scripts/components/pre/pre.test.js, src/webapp/scripts/components/search-input/search-input.html, src/webapp/scripts/components/search-input/search-input.test.js, src/webapp/scripts/components/welcome/welcome.html, src/webapp/styles/_native.styl, src/webapp/styles/input.styl, src/webapp/styles/paragraph.styl, src/webapp/styles/pre.styl, src/webapp/styles/search-input.styl
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/95
Removed all native styles created the respective components to accommodate them.
=> Native styles remove

package-lock.json, package.json, src/cli/docs/build.txt, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js
Resolves #94 
Added an argument (--port) to the build command
=> Add ability to pass a server port to listen on

package-lock.json, package.json, src/cli/services/config.js, src/cli/services/config.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/90
=> Allow pitsby.config.js as config filename

README.md, docs/configuration.md, docs/contributing.md, package-lock.json, package.json, src/cli/docs/build.txt, src/cli/services/build.js, src/cli/services/build.test.js
Updated instances of configuration filename on readme, doc and test files.
=> Docs update

.circleci/prepare.js, .gitignore, docs/configuration.md, package-lock.json, package.json, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/webapp-logo-generator.js, src/cli/services/webapp-logo-generator.test.js, src/webapp/scripts/components/logo/logo-template.html, src/webapp/scripts/components/logo/logo.html
Ref.: https://github.com/glorious-codes/glorious-pitsby/issues/78
=> Logo customisation

docs/configuration.md, package-lock.json, package.json, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/webapp-html-index-customisation.js, src/cli/services/webapp-html-index-customisation.test.js, src/cli/services/webapp-html-index-generator.js, src/cli/services/webapp-html-index-generator.test.js, src/webapp/index-template.html, webpack.conf.base.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/78
=> Favicon customisation

package-lock.json, package.json, src/webapp/styles/main.styl, src/webapp/styles/viewport.styl
=> Minor visual fixes

package-lock.json, package.json, src/webapp/styles/main.styl, src/webapp/styles/welcome.styl
Completes https://github.com/glorious-codes/glorious-pitsby/issues/107
- Make main component fill at least 100% of viewport height
- Fix welcome placement inside main component
=> Visual fixes

docs/configuration.md, package-lock.json, package.json, src/cli/services/webapp-html-index-customisation.js, src/cli/services/webapp-html-index-customisation.test.js, src/cli/services/webapp-html-index-generator.test.js, src/cli/services/webapp-index-generator.test.js, src/webapp/index-template.html, src/webapp/scripts/index-template.js, src/webapp/scripts/index-template.test.js, src/webapp/scripts/services/stylesheets-order.js, src/webapp/scripts/services/stylesheets-order.test.js
=> Allow custom global styles

docs/documentation.md, package-lock.json, package.json, src/webapp/scripts/components/external-component-properties-list/external-component-properties-list.html, src/webapp/scripts/components/external-component-properties-list/external-component-properties-list.test.js, src/webapp/scripts/components/external-component/external-component.html, src/webapp/scripts/components/index.js, src/webapp/scripts/components/tag/tag.html, src/webapp/scripts/components/tag/tag.js, src/webapp/scripts/components/tag/tag.test.js, src/webapp/styles/_variables.styl, src/webapp/styles/external-component-properties-list.styl, src/webapp/styles/external-component.styl, src/webapp/styles/tag.styl, src/webapp/styles/viewport.styl
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/113
=> Allow users to show an optional deprecation tag for components and their props

package-lock.json, package.json, src/webapp/scripts/components/external-component-preview/external-component-preview.js, src/webapp/scripts/components/external-component-preview/external-component-preview.test.js, src/webapp/scripts/services/page-fold.js, src/webapp/scripts/services/page-fold.test.js, src/webapp/scripts/services/pubsub.js, src/webapp/scripts/services/window.js, src/webapp/scripts/services/window.test.js
=> Rendering on demand

package-lock.json, package.json, src/webapp/scripts/components/components-menu-item/components-menu-item.html, src/webapp/scripts/components/components-menu-item/components-menu-item.js, src/webapp/scripts/components/components-menu-item/components-menu-item.test.js, src/webapp/scripts/components/components-menu/components-menu.html, src/webapp/scripts/components/components-menu/components-menu.js, src/webapp/scripts/components/components-menu/components-menu.test.js, src/webapp/scripts/components/sidebar/sidebar.html, src/webapp/scripts/components/sidebar/sidebar.js, src/webapp/scripts/components/sidebar/sidebar.test.js, src/webapp/styles/code-editor.styl, src/webapp/styles/external-components-playground.styl
Closing sidebar on menu item click when it has no children (mobile)
=> Playground improvements

docs/configuration.md, package-lock.json, package.json, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, src/cli/services/webapp-index-generator.js, src/cli/services/webapp-index-generator.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/121
=> Bundle improvement

package-lock.json, package.json, src/webapp/styles/logo.styl
Limited logo height to 40px on mobile.
=> Mobile logo size

.eslintrc.json, package-lock.json, package.json, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, src/webapp/scripts/services/vue-component-builder.js, src/webapp/scripts/services/vue-component-builder.test.js
Resolves #116 
- Allow self closing tags on Vue templates
=> Vue templates improvement

package-lock.json, package.json, src/webapp/scripts/components/components-menu-item/components-menu-item.html, src/webapp/scripts/components/components-menu/components-menu.html, src/webapp/scripts/components/components-menu/components-menu.js, src/webapp/scripts/components/components-menu/components-menu.test.js, src/webapp/scripts/services/components-menu.js, src/webapp/scripts/services/components-menu.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/126
Highlight active item properly when search input is not blank.
=> Search improvement

package-lock.json, package.json, src/webapp/scripts/services/external-components-playground-default-code-builder.js, src/webapp/scripts/services/external-components-playground-default-code-builder.test.js
=> Playground improvement

package-lock.json, package.json, src/webapp/scripts/services/vanilla-component-builder.js, src/webapp/scripts/services/vanilla-component-builder.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/140
Execute vanilla component example's controller async.
=> Vanilla examples improvement

package-lock.json, package.json
=> Bump angular version

.circleci/config.yml, package-lock.json, package.json, src/cli/services/webapp-logo-generator.js, src/cli/services/webapp-logo-generator.test.js
Added a fingerprint to the custom logo background image url
=> Improve custom logo style

package-lock.json, package.json
Set angular version as 1.7.8 since [cdnjs](https://cdnjs.com/libraries/angular.js) seems not to serve the latest (1.7.9) version.
=> Downgrade angular version

package-lock.json, package.json, src/cli/services/cdn.js, src/cli/services/cdn.test.js, src/cli/services/webapp-html-index-generator.test.js, src/webapp/scripts/components/external-component-methods-list/external-component-methods-list.html, src/webapp/styles/external-component-methods-list.styl
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/150
**Preview**
=> Improve method's name on methods table

package-lock.json, package.json, src/webapp/styles/engine-menu.styl
=> Improve engine menu link alignment

.circleci/config.yml, README.md, package-lock.json, package.json, src/cli/services/cdn.test.js
- Config coveralls
- Bump webpack deps
- Bump angular dep
=> Config Coveralls

package-lock.json, package.json, src/webapp/styles/logo.styl, src/webapp/styles/topbar.styl
- Minor improvements on logo appearance.
- Remove bad important style declaration
=> Improve logo styles

package-lock.json, package.json, src/webapp/scripts/resources/components.js, src/webapp/scripts/resources/components.test.js, src/webapp/styles/credits.styl
Resolves #170 
Also improves the readability of the credits link at the bottom of the sidebar.
**Preview**
=> Fix components order on components menu

.eslintrc.json, package-lock.json, package.json, src/webapp/images/open.svg, src/webapp/scripts/components/external-component-code/external-component-code.js, src/webapp/scripts/components/external-component-code/external-component-code.test.js, src/webapp/scripts/components/external-component-example-edit-link/external-component-example-edit-link.html, src/webapp/scripts/components/external-component-example-edit-link/external-component-example-edit-link.js, src/webapp/scripts/components/external-component-example-edit-link/external-component-example-edit-link.test.js, src/webapp/scripts/components/external-component-example/external-component-example.html, src/webapp/scripts/components/external-component-example/external-component-example.test.js, src/webapp/scripts/components/external-components-playground/external-components-playground.html, src/webapp/scripts/components/external-components-playground/external-components-playground.js, src/webapp/scripts/components/external-components-playground/external-components-playground.test.js, src/webapp/scripts/components/index.js, src/webapp/scripts/constants/routes.js, src/webapp/scripts/services/playground-code-search-param.js, src/webapp/scripts/services/playground-code-search-param.test.js, src/webapp/scripts/services/vue-controller-indentation.js, src/webapp/scripts/services/vue-controller-syntax.js, src/webapp/scripts/services/vue-controller-syntax.test.js, src/webapp/styles/external-component-example-edit-link.styl, src/webapp/styles/external-component-example.styl, src/webapp/styles/external-components-playground.styl, webpack.conf.dev.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/175
**Preview**
=> Add playground link to each component example

package-lock.json, package.json
New version with [almost] dependency updated to its latest version.
=> Bump version to 1.30.12

package-lock.json, package.json, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/215
=> Disable invasive webpack warning overlay in the browser

package-lock.json, package.json, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, webpack.conf.base.js
Trying to make compiled files watching work again.
=> Improve dev server config

package-lock.json, package.json, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js
Still trying to fix live reload.
=> Add socket url to webpack entry to improve live reload

package-lock.json, package.json, src/cli/services/build.js, src/cli/services/build.test.js, src/cli/services/docs-generator.js, src/cli/services/docs-generator.test.js, src/cli/services/external-assets-generator.js, src/cli/services/external-assets-generator.test.js, src/cli/services/file.js, src/cli/services/file.test.js, src/cli/services/logger.js, src/cli/services/logger.test.js, src/cli/services/watch.js, src/cli/services/watch.test.js, src/cli/services/webapp-html-index-customisation.js
This pull request introduces the necessary changes to improve the look of logged messages.
=> Improve logs style

src/webapp/scripts/services/external-components-playground-default-code-builder.js, src/webapp/scripts/services/external-components-playground-default-code-builder.test.js
Minor improvement on example code shown inside vanilla playground
=> Improve example code on vanilla playground

.eslintrc, src/cli/services/webapp-html-index-generator.js, src/cli/services/webapp-html-index-generator.test.js
Resolves https://github.com/glorious-codes/glorious-pitsby/issues/240
=> Fix color scheme change listener parser

jest.config.js, package-lock.json, package.json, src/webapp/scripts/resources/data.js, src/webapp/scripts/resources/data.test.js
Resolves: https://github.com/glorious-codes/glorious-pitsby/issues/245
Also:
- cache date resource responses
- update browsers list db
=> Axios upgrade
